#docker run --name=mysql1 -p 33036:3306 -e MYSQL_ROOT_PASSWORD=pass -d mysql/mysql-server:8.0
version: '3.4'

services:
  database:
    image: mysql
    container_name: dev-db
    ports:
      - "33036:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_HOST: '%'